name: build package
on:
  push:
    branches:
      - packages-configuration

env:
  IMAGE_NAME: docker-terraform

jobs:
  build-and-publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Load Terraform version
        id: version
        run: echo "::set-output name=TERRAFORM_VERSION::$(cat ./terraform_version.txt)"

      - name: Build Docker image
        run: DOCKER_BUILDKIT=1 docker build -t ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.TERRAFORM_VERSION }} -f ./Dockerfile .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Push Docker image to GitHub Container Registry
        run: docker push ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.TERRAFORM_VERSION }}
